# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
MD007:
  indent: 4

# remove top-lvel heading b/c have some include files
MD041: false

# Remove line length limit
MD013: false

# Remove "fenced code blocks should have language specified"
MD040: false

# Remove "no inline HTML"
MD046: false

# Remove no in line HTML
MD033: false

# Remove "no emphasis as heading"
MD036: false
