#!/usr/bin/env bash
# Local validation workflows and try to build documentation locally
echo "1/5 Running precommit"
pre-commit run --all-files

echo "2/5 Validating table schemas"
pre-commit run --all-files
echo "Processing file: $file"
for file in spec/*schema.json; do
  echo "Validating: $file"
  frictionless validate $file
done

echo "3/5 Validating datapackage"
json-schema-cli validate https://specs.frictionlessdata.io/schemas/data-package.json spec/datapackage.json

echo "4/5 Validating sample data"
for file in samples/**/TIDES/datapackage.json; do
    echo "Validating: $file"
    frictionless validate --schema-sync $file
done

echo "5/5 Building documentation"
mkdocs build
