name: Validate Frictionless Data Package Schema for Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'spec/tides.spec.json$'

jobs:
  validate_data_package:
    name: Validate Frictionless Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Data Package schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: "https://specs.frictionlessdata.io/schemas/data-package.json"
          json_path_pattern: ^spec/tides\.spec\.json$
          send_comment: true
          clear_comments: true
