name: Validate Frictionless Data Package Schema for Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'spec/tides.spec.json'

jobs:
  validate_data_package:
    name: Validate Frictionless Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Data Package schema
        uses: TIDES-transit/json-schema-validator@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: spec/tides-data-package.json
          json_path_pattern: ^spec/tides\.spec\.json$
          send_comment: false
          clear_comments: false
